services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: localdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # for apps
      - "15672:15672"    # management UI

  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache
    ports:
      - "8545:8545"
    command:
      - --accounts=10
      - --defaultBalanceEther=1000
      - --mnemonic="myth like bonus scare over problem client lizard pioneer submit female collect"

volumes:
  pg_data: